/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace MeterOracle {
  export type ProducerStruct = {
    isRegistered: boolean;
    maxCapacityKwh: BigNumberish;
    totalMintedKwh: BigNumberish;
    readingCount: BigNumberish;
  };

  export type ProducerStructOutput = [
    isRegistered: boolean,
    maxCapacityKwh: bigint,
    totalMintedKwh: bigint,
    readingCount: bigint
  ] & {
    isRegistered: boolean;
    maxCapacityKwh: bigint;
    totalMintedKwh: bigint;
    readingCount: bigint;
  };
}

export interface MeterOracleInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "energyToken"
      | "getAllProducers"
      | "getProducer"
      | "isProducerRegistered"
      | "owner"
      | "registerProducer"
      | "renounceOwnership"
      | "submitReading"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "MeterReadingSubmitted"
      | "OwnershipTransferred"
      | "ProducerRegistered"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "energyToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAllProducers",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getProducer",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isProducerRegistered",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "registerProducer",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "submitReading",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "energyToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllProducers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProducer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isProducerRegistered",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerProducer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitReading",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace MeterReadingSubmittedEvent {
  export type InputTuple = [
    producer: AddressLike,
    kwhProduced: BigNumberish,
    totalMintedKwh: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    producer: string,
    kwhProduced: bigint,
    totalMintedKwh: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    producer: string;
    kwhProduced: bigint;
    totalMintedKwh: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProducerRegisteredEvent {
  export type InputTuple = [
    producer: AddressLike,
    maxCapacityKwh: BigNumberish
  ];
  export type OutputTuple = [producer: string, maxCapacityKwh: bigint];
  export interface OutputObject {
    producer: string;
    maxCapacityKwh: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface MeterOracle extends BaseContract {
  connect(runner?: ContractRunner | null): MeterOracle;
  waitForDeployment(): Promise<this>;

  interface: MeterOracleInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  energyToken: TypedContractMethod<[], [string], "view">;

  getAllProducers: TypedContractMethod<[], [string[]], "view">;

  getProducer: TypedContractMethod<
    [producer: AddressLike],
    [MeterOracle.ProducerStructOutput],
    "view"
  >;

  isProducerRegistered: TypedContractMethod<
    [producer: AddressLike],
    [boolean],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  registerProducer: TypedContractMethod<
    [producer: AddressLike, maxCapacityKwh: BigNumberish],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  submitReading: TypedContractMethod<
    [producer: AddressLike, kwhProduced: BigNumberish],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "energyToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getAllProducers"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getProducer"
  ): TypedContractMethod<
    [producer: AddressLike],
    [MeterOracle.ProducerStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "isProducerRegistered"
  ): TypedContractMethod<[producer: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "registerProducer"
  ): TypedContractMethod<
    [producer: AddressLike, maxCapacityKwh: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "submitReading"
  ): TypedContractMethod<
    [producer: AddressLike, kwhProduced: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "MeterReadingSubmitted"
  ): TypedContractEvent<
    MeterReadingSubmittedEvent.InputTuple,
    MeterReadingSubmittedEvent.OutputTuple,
    MeterReadingSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "ProducerRegistered"
  ): TypedContractEvent<
    ProducerRegisteredEvent.InputTuple,
    ProducerRegisteredEvent.OutputTuple,
    ProducerRegisteredEvent.OutputObject
  >;

  filters: {
    "MeterReadingSubmitted(address,uint256,uint256,uint256)": TypedContractEvent<
      MeterReadingSubmittedEvent.InputTuple,
      MeterReadingSubmittedEvent.OutputTuple,
      MeterReadingSubmittedEvent.OutputObject
    >;
    MeterReadingSubmitted: TypedContractEvent<
      MeterReadingSubmittedEvent.InputTuple,
      MeterReadingSubmittedEvent.OutputTuple,
      MeterReadingSubmittedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "ProducerRegistered(address,uint256)": TypedContractEvent<
      ProducerRegisteredEvent.InputTuple,
      ProducerRegisteredEvent.OutputTuple,
      ProducerRegisteredEvent.OutputObject
    >;
    ProducerRegistered: TypedContractEvent<
      ProducerRegisteredEvent.InputTuple,
      ProducerRegisteredEvent.OutputTuple,
      ProducerRegisteredEvent.OutputObject
    >;
  };
}
