/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace EnergyMarket {
  export type OfferStruct = {
    id: BigNumberish;
    producer: AddressLike;
    quantityKwh: BigNumberish;
    pricePerKwhWei: BigNumberish;
    remainingKwh: BigNumberish;
    isActive: boolean;
    createdAt: BigNumberish;
    updatedAt: BigNumberish;
  };

  export type OfferStructOutput = [
    id: bigint,
    producer: string,
    quantityKwh: bigint,
    pricePerKwhWei: bigint,
    remainingKwh: bigint,
    isActive: boolean,
    createdAt: bigint,
    updatedAt: bigint
  ] & {
    id: bigint;
    producer: string;
    quantityKwh: bigint;
    pricePerKwhWei: bigint;
    remainingKwh: bigint;
    isActive: boolean;
    createdAt: bigint;
    updatedAt: bigint;
  };

  export type TradeStruct = {
    id: BigNumberish;
    offerId: BigNumberish;
    producer: AddressLike;
    consumer: AddressLike;
    quantityKwh: BigNumberish;
    unitPriceWei: BigNumberish;
    totalPriceWei: BigNumberish;
    timestamp: BigNumberish;
  };

  export type TradeStructOutput = [
    id: bigint,
    offerId: bigint,
    producer: string,
    consumer: string,
    quantityKwh: bigint,
    unitPriceWei: bigint,
    totalPriceWei: bigint,
    timestamp: bigint
  ] & {
    id: bigint;
    offerId: bigint;
    producer: string;
    consumer: string;
    quantityKwh: bigint;
    unitPriceWei: bigint;
    totalPriceWei: bigint;
    timestamp: bigint;
  };
}

export interface EnergyMarketInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "buyEnergy"
      | "cancelOffer"
      | "certificateContract"
      | "createOffer"
      | "energyToken"
      | "getActiveOffers"
      | "getAllOffers"
      | "getOffer"
      | "getOfferCount"
      | "getTradeCount"
      | "getTradeHistory"
      | "getTradesByAddress"
      | "owner"
      | "renounceOwnership"
      | "reputationSystem"
      | "setCertificateContract"
      | "setReputationSystem"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CertificateContractUpdated"
      | "EnergySold"
      | "OfferCancelled"
      | "OfferCreated"
      | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "buyEnergy",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelOffer",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "certificateContract",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "createOffer",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "energyToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getActiveOffers",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAllOffers",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getOffer",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getOfferCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTradeCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTradeHistory",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTradesByAddress",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "reputationSystem",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setCertificateContract",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setReputationSystem",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "buyEnergy", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "cancelOffer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "certificateContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createOffer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "energyToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getActiveOffers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllOffers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getOffer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getOfferCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTradeCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTradeHistory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTradesByAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "reputationSystem",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setCertificateContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setReputationSystem",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace CertificateContractUpdatedEvent {
  export type InputTuple = [
    previousCertificateContract: AddressLike,
    newCertificateContract: AddressLike
  ];
  export type OutputTuple = [
    previousCertificateContract: string,
    newCertificateContract: string
  ];
  export interface OutputObject {
    previousCertificateContract: string;
    newCertificateContract: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EnergySoldEvent {
  export type InputTuple = [
    offerId: BigNumberish,
    tradeId: BigNumberish,
    consumer: AddressLike,
    producer: AddressLike,
    quantityKwh: BigNumberish,
    totalPriceWei: BigNumberish
  ];
  export type OutputTuple = [
    offerId: bigint,
    tradeId: bigint,
    consumer: string,
    producer: string,
    quantityKwh: bigint,
    totalPriceWei: bigint
  ];
  export interface OutputObject {
    offerId: bigint;
    tradeId: bigint;
    consumer: string;
    producer: string;
    quantityKwh: bigint;
    totalPriceWei: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OfferCancelledEvent {
  export type InputTuple = [
    offerId: BigNumberish,
    producer: AddressLike,
    remainingKwh: BigNumberish
  ];
  export type OutputTuple = [
    offerId: bigint,
    producer: string,
    remainingKwh: bigint
  ];
  export interface OutputObject {
    offerId: bigint;
    producer: string;
    remainingKwh: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OfferCreatedEvent {
  export type InputTuple = [
    offerId: BigNumberish,
    producer: AddressLike,
    quantityKwh: BigNumberish,
    pricePerKwhWei: BigNumberish
  ];
  export type OutputTuple = [
    offerId: bigint,
    producer: string,
    quantityKwh: bigint,
    pricePerKwhWei: bigint
  ];
  export interface OutputObject {
    offerId: bigint;
    producer: string;
    quantityKwh: bigint;
    pricePerKwhWei: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface EnergyMarket extends BaseContract {
  connect(runner?: ContractRunner | null): EnergyMarket;
  waitForDeployment(): Promise<this>;

  interface: EnergyMarketInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  buyEnergy: TypedContractMethod<
    [offerId: BigNumberish, quantityKwh: BigNumberish],
    [void],
    "payable"
  >;

  cancelOffer: TypedContractMethod<
    [offerId: BigNumberish],
    [void],
    "nonpayable"
  >;

  certificateContract: TypedContractMethod<[], [string], "view">;

  createOffer: TypedContractMethod<
    [quantityKwh: BigNumberish, pricePerKwhWei: BigNumberish],
    [void],
    "nonpayable"
  >;

  energyToken: TypedContractMethod<[], [string], "view">;

  getActiveOffers: TypedContractMethod<
    [],
    [EnergyMarket.OfferStructOutput[]],
    "view"
  >;

  getAllOffers: TypedContractMethod<
    [],
    [EnergyMarket.OfferStructOutput[]],
    "view"
  >;

  getOffer: TypedContractMethod<
    [offerId: BigNumberish],
    [EnergyMarket.OfferStructOutput],
    "view"
  >;

  getOfferCount: TypedContractMethod<[], [bigint], "view">;

  getTradeCount: TypedContractMethod<[], [bigint], "view">;

  getTradeHistory: TypedContractMethod<
    [],
    [EnergyMarket.TradeStructOutput[]],
    "view"
  >;

  getTradesByAddress: TypedContractMethod<
    [user: AddressLike],
    [EnergyMarket.TradeStructOutput[]],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  reputationSystem: TypedContractMethod<[], [string], "view">;

  setCertificateContract: TypedContractMethod<
    [certificateAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  setReputationSystem: TypedContractMethod<
    [reputationAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "buyEnergy"
  ): TypedContractMethod<
    [offerId: BigNumberish, quantityKwh: BigNumberish],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "cancelOffer"
  ): TypedContractMethod<[offerId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "certificateContract"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "createOffer"
  ): TypedContractMethod<
    [quantityKwh: BigNumberish, pricePerKwhWei: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "energyToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getActiveOffers"
  ): TypedContractMethod<[], [EnergyMarket.OfferStructOutput[]], "view">;
  getFunction(
    nameOrSignature: "getAllOffers"
  ): TypedContractMethod<[], [EnergyMarket.OfferStructOutput[]], "view">;
  getFunction(
    nameOrSignature: "getOffer"
  ): TypedContractMethod<
    [offerId: BigNumberish],
    [EnergyMarket.OfferStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getOfferCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getTradeCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getTradeHistory"
  ): TypedContractMethod<[], [EnergyMarket.TradeStructOutput[]], "view">;
  getFunction(
    nameOrSignature: "getTradesByAddress"
  ): TypedContractMethod<
    [user: AddressLike],
    [EnergyMarket.TradeStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "reputationSystem"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setCertificateContract"
  ): TypedContractMethod<
    [certificateAddress: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setReputationSystem"
  ): TypedContractMethod<
    [reputationAddress: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "CertificateContractUpdated"
  ): TypedContractEvent<
    CertificateContractUpdatedEvent.InputTuple,
    CertificateContractUpdatedEvent.OutputTuple,
    CertificateContractUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "EnergySold"
  ): TypedContractEvent<
    EnergySoldEvent.InputTuple,
    EnergySoldEvent.OutputTuple,
    EnergySoldEvent.OutputObject
  >;
  getEvent(
    key: "OfferCancelled"
  ): TypedContractEvent<
    OfferCancelledEvent.InputTuple,
    OfferCancelledEvent.OutputTuple,
    OfferCancelledEvent.OutputObject
  >;
  getEvent(
    key: "OfferCreated"
  ): TypedContractEvent<
    OfferCreatedEvent.InputTuple,
    OfferCreatedEvent.OutputTuple,
    OfferCreatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "CertificateContractUpdated(address,address)": TypedContractEvent<
      CertificateContractUpdatedEvent.InputTuple,
      CertificateContractUpdatedEvent.OutputTuple,
      CertificateContractUpdatedEvent.OutputObject
    >;
    CertificateContractUpdated: TypedContractEvent<
      CertificateContractUpdatedEvent.InputTuple,
      CertificateContractUpdatedEvent.OutputTuple,
      CertificateContractUpdatedEvent.OutputObject
    >;

    "EnergySold(uint256,uint256,address,address,uint256,uint256)": TypedContractEvent<
      EnergySoldEvent.InputTuple,
      EnergySoldEvent.OutputTuple,
      EnergySoldEvent.OutputObject
    >;
    EnergySold: TypedContractEvent<
      EnergySoldEvent.InputTuple,
      EnergySoldEvent.OutputTuple,
      EnergySoldEvent.OutputObject
    >;

    "OfferCancelled(uint256,address,uint256)": TypedContractEvent<
      OfferCancelledEvent.InputTuple,
      OfferCancelledEvent.OutputTuple,
      OfferCancelledEvent.OutputObject
    >;
    OfferCancelled: TypedContractEvent<
      OfferCancelledEvent.InputTuple,
      OfferCancelledEvent.OutputTuple,
      OfferCancelledEvent.OutputObject
    >;

    "OfferCreated(uint256,address,uint256,uint256)": TypedContractEvent<
      OfferCreatedEvent.InputTuple,
      OfferCreatedEvent.OutputTuple,
      OfferCreatedEvent.OutputObject
    >;
    OfferCreated: TypedContractEvent<
      OfferCreatedEvent.InputTuple,
      OfferCreatedEvent.OutputTuple,
      OfferCreatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
