/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace IEnergyCertificate {
  export type CertificateDataStruct = {
    buyer: AddressLike;
    producer: AddressLike;
    kwhAmount: BigNumberish;
    priceWei: BigNumberish;
    tradeId: BigNumberish;
    issuedAt: BigNumberish;
  };

  export type CertificateDataStructOutput = [
    buyer: string,
    producer: string,
    kwhAmount: bigint,
    priceWei: bigint,
    tradeId: bigint,
    issuedAt: bigint
  ] & {
    buyer: string;
    producer: string;
    kwhAmount: bigint;
    priceWei: bigint;
    tradeId: bigint;
    issuedAt: bigint;
  };
}

export interface IEnergyCertificateInterface extends Interface {
  getFunction(nameOrSignature: "mint"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "mint",
    values: [AddressLike, IEnergyCertificate.CertificateDataStruct]
  ): string;

  decodeFunctionResult(functionFragment: "mint", data: BytesLike): Result;
}

export interface IEnergyCertificate extends BaseContract {
  connect(runner?: ContractRunner | null): IEnergyCertificate;
  waitForDeployment(): Promise<this>;

  interface: IEnergyCertificateInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  mint: TypedContractMethod<
    [to: AddressLike, data: IEnergyCertificate.CertificateDataStruct],
    [bigint],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "mint"
  ): TypedContractMethod<
    [to: AddressLike, data: IEnergyCertificate.CertificateDataStruct],
    [bigint],
    "nonpayable"
  >;

  filters: {};
}
