/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IEnergyCertificate,
  IEnergyCertificateInterface,
} from "../../../contracts/EnergyMarket.sol/IEnergyCertificate";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        components: [
          {
            internalType: "address",
            name: "buyer",
            type: "address",
          },
          {
            internalType: "address",
            name: "producer",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "kwhAmount",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "priceWei",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "tradeId",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "issuedAt",
            type: "uint256",
          },
        ],
        internalType: "struct IEnergyCertificate.CertificateData",
        name: "data",
        type: "tuple",
      },
    ],
    name: "mint",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IEnergyCertificate__factory {
  static readonly abi = _abi;
  static createInterface(): IEnergyCertificateInterface {
    return new Interface(_abi) as IEnergyCertificateInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IEnergyCertificate {
    return new Contract(address, _abi, runner) as unknown as IEnergyCertificate;
  }
}
