/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace ReputationSystem {
  export type RatingStruct = {
    consumer: AddressLike;
    producer: AddressLike;
    score: BigNumberish;
    tradeId: BigNumberish;
    timestamp: BigNumberish;
  };

  export type RatingStructOutput = [
    consumer: string,
    producer: string,
    score: bigint,
    tradeId: bigint,
    timestamp: bigint
  ] & {
    consumer: string;
    producer: string;
    score: bigint;
    tradeId: bigint;
    timestamp: bigint;
  };

  export type ProducerReputationStruct = {
    totalScore: BigNumberish;
    ratingCount: BigNumberish;
    averageScore: BigNumberish;
  };

  export type ProducerReputationStructOutput = [
    totalScore: bigint,
    ratingCount: bigint,
    averageScore: bigint
  ] & { totalScore: bigint; ratingCount: bigint; averageScore: bigint };
}

export interface ReputationSystemInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "authorizedMarket"
      | "canRate"
      | "getRatingsByProducer"
      | "getReputation"
      | "owner"
      | "ratingCounter"
      | "ratings"
      | "ratingsByConsumer"
      | "ratingsByProducer"
      | "recordTrade"
      | "renounceOwnership"
      | "reputations"
      | "setAuthorizedMarket"
      | "submitRating"
      | "tradeConsumer"
      | "tradeProducer"
      | "tradeRated"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "OwnershipTransferred"
      | "RatingSubmitted"
      | "TradeRecorded"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "authorizedMarket",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "canRate",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRatingsByProducer",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getReputation",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "ratingCounter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ratings",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "ratingsByConsumer",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "ratingsByProducer",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "recordTrade",
    values: [BigNumberish, AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "reputations",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setAuthorizedMarket",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "submitRating",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "tradeConsumer",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "tradeProducer",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "tradeRated",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "authorizedMarket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "canRate", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getRatingsByProducer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getReputation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "ratingCounter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "ratings", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "ratingsByConsumer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ratingsByProducer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recordTrade",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "reputations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAuthorizedMarket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitRating",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tradeConsumer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tradeProducer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "tradeRated", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RatingSubmittedEvent {
  export type InputTuple = [
    ratingId: BigNumberish,
    consumer: AddressLike,
    producer: AddressLike,
    score: BigNumberish,
    tradeId: BigNumberish
  ];
  export type OutputTuple = [
    ratingId: bigint,
    consumer: string,
    producer: string,
    score: bigint,
    tradeId: bigint
  ];
  export interface OutputObject {
    ratingId: bigint;
    consumer: string;
    producer: string;
    score: bigint;
    tradeId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TradeRecordedEvent {
  export type InputTuple = [
    tradeId: BigNumberish,
    consumer: AddressLike,
    producer: AddressLike
  ];
  export type OutputTuple = [
    tradeId: bigint,
    consumer: string,
    producer: string
  ];
  export interface OutputObject {
    tradeId: bigint;
    consumer: string;
    producer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ReputationSystem extends BaseContract {
  connect(runner?: ContractRunner | null): ReputationSystem;
  waitForDeployment(): Promise<this>;

  interface: ReputationSystemInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  authorizedMarket: TypedContractMethod<[], [string], "view">;

  canRate: TypedContractMethod<
    [tradeId: BigNumberish, consumer: AddressLike],
    [boolean],
    "view"
  >;

  getRatingsByProducer: TypedContractMethod<
    [producer: AddressLike],
    [ReputationSystem.RatingStructOutput[]],
    "view"
  >;

  getReputation: TypedContractMethod<
    [producer: AddressLike],
    [ReputationSystem.ProducerReputationStructOutput],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  ratingCounter: TypedContractMethod<[], [bigint], "view">;

  ratings: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, bigint, bigint] & {
        consumer: string;
        producer: string;
        score: bigint;
        tradeId: bigint;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  ratingsByConsumer: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  ratingsByProducer: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  recordTrade: TypedContractMethod<
    [tradeId: BigNumberish, consumer: AddressLike, producer: AddressLike],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  reputations: TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, bigint] & {
        totalScore: bigint;
        ratingCount: bigint;
        averageScore: bigint;
      }
    ],
    "view"
  >;

  setAuthorizedMarket: TypedContractMethod<
    [market: AddressLike],
    [void],
    "nonpayable"
  >;

  submitRating: TypedContractMethod<
    [tradeId: BigNumberish, score: BigNumberish],
    [void],
    "nonpayable"
  >;

  tradeConsumer: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  tradeProducer: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  tradeRated: TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "authorizedMarket"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "canRate"
  ): TypedContractMethod<
    [tradeId: BigNumberish, consumer: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRatingsByProducer"
  ): TypedContractMethod<
    [producer: AddressLike],
    [ReputationSystem.RatingStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getReputation"
  ): TypedContractMethod<
    [producer: AddressLike],
    [ReputationSystem.ProducerReputationStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ratingCounter"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "ratings"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, bigint, bigint] & {
        consumer: string;
        producer: string;
        score: bigint;
        tradeId: bigint;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "ratingsByConsumer"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "ratingsByProducer"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "recordTrade"
  ): TypedContractMethod<
    [tradeId: BigNumberish, consumer: AddressLike, producer: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "reputations"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, bigint] & {
        totalScore: bigint;
        ratingCount: bigint;
        averageScore: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "setAuthorizedMarket"
  ): TypedContractMethod<[market: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "submitRating"
  ): TypedContractMethod<
    [tradeId: BigNumberish, score: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "tradeConsumer"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "tradeProducer"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "tradeRated"
  ): TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "RatingSubmitted"
  ): TypedContractEvent<
    RatingSubmittedEvent.InputTuple,
    RatingSubmittedEvent.OutputTuple,
    RatingSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "TradeRecorded"
  ): TypedContractEvent<
    TradeRecordedEvent.InputTuple,
    TradeRecordedEvent.OutputTuple,
    TradeRecordedEvent.OutputObject
  >;

  filters: {
    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "RatingSubmitted(uint256,address,address,uint8,uint256)": TypedContractEvent<
      RatingSubmittedEvent.InputTuple,
      RatingSubmittedEvent.OutputTuple,
      RatingSubmittedEvent.OutputObject
    >;
    RatingSubmitted: TypedContractEvent<
      RatingSubmittedEvent.InputTuple,
      RatingSubmittedEvent.OutputTuple,
      RatingSubmittedEvent.OutputObject
    >;

    "TradeRecorded(uint256,address,address)": TypedContractEvent<
      TradeRecordedEvent.InputTuple,
      TradeRecordedEvent.OutputTuple,
      TradeRecordedEvent.OutputObject
    >;
    TradeRecorded: TypedContractEvent<
      TradeRecordedEvent.InputTuple,
      TradeRecordedEvent.OutputTuple,
      TradeRecordedEvent.OutputObject
    >;
  };
}
